import pandas as pd
import numpy as np
from ta.trend import MACD
from ta.momentum import RSIIndicator
from ta.volatility import BollingerBands

class FeatureEngineer:
    def __init__(self):
        self.feature_columns = []
    
    def create_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Create ML features from OHLCV data
        
        Args:
            df: DataFrame with columns [open, high, low, close, volume]
        
        Returns:
            DataFrame with added feature columns
        """
        # Ensure numerical types
        numeric_cols = ['open', 'high', 'low', 'close', 'volume']
        for col in numeric_cols:
            df[col] = pd.to_numeric(df[col])

        # Technical Indicators
        # RSI
        df['rsi_14'] = RSIIndicator(close=df['close'], window=14).rsi()
        
        # MACD
        macd = MACD(close=df['close'])
        df['macd'] = macd.macd()
        df['macd_signal'] = macd.macd_signal()
        df['macd_diff'] = macd.macd_diff()
        
        # Bollinger Bands
        bb = BollingerBands(close=df['close'])
        df['bb_high'] = bb.bollinger_hband()
        df['bb_low'] = bb.bollinger_lband()
        df['bb_mid'] = bb.bollinger_mavg()
        # BB Width: normalized volatility
        # Avoid division by zero
        df['bb_width'] = (df['bb_high'] - df['bb_low']) / df['bb_mid'].replace(0, np.nan)
        
        # Price Action
        df['returns'] = df['close'].pct_change()
        # Log returns for better statistical properties
        df['log_returns'] = np.log(df['close'] / df['close'].shift(1))
        
        # Candle shape
        df['high_low_ratio'] = df['high'] / df['low']
        df['close_open_ratio'] = df['close'] / df['open']
        
        # Volume Analysis
        df['volume_sma_20'] = df['volume'].rolling(window=20).mean()
        df['volume_ratio'] = df['volume'] / df['volume_sma_20'].replace(0, np.nan)
        
        # Price vs Moving Averages
        df['sma_20'] = df['close'].rolling(window=20).mean()
        df['sma_50'] = df['close'].rolling(window=50).mean()
        df['price_sma20_ratio'] = df['close'] / df['sma_20']
        df['price_sma50_ratio'] = df['close'] / df['sma_50']
        
        # Volatility (Rolling Std Dev of returns)
        df['volatility_20'] = df['returns'].rolling(window=20).std()
        
        # Target Generation (Labeling)
        # Predict if price will increase > 1% in next hour (assuming 5m candles -> 12 periods)
        # Note: Shift(-12) looks into the future 1 hour
        future_close = df['close'].shift(-12)
        current_close = df['close']
        
        # Target: 1 if price increases > 1%, 0 otherwise
        # threshold 1.01 = 1% gain
        df['target'] = (future_close > current_close * 1.01).astype(int)
        
        # Drop rows with NaN (generated by rolling windows or shift)
        # We need to be careful not to drop all data if history is short
        # Indicators need up to ~50 periods
        df = df.dropna()
        
        self.feature_columns = [
            'rsi_14', 'macd', 'macd_signal', 'macd_diff',
            'bb_width', 'returns', 'log_returns', 'high_low_ratio',
            'close_open_ratio',
            'volume_ratio', 'price_sma20_ratio', 'price_sma50_ratio',
            'volatility_20'
        ]
        
        return df
    
    def get_feature_importance(self, model):
        """Get feature importance for explainability"""
        # XGBoost provides feature importances
        importances = model.feature_importances_
        return pd.DataFrame({
            'feature': self.feature_columns,
            'importance': importances
        }).sort_values('importance', ascending=False)
