import { StrategyPhase } from '@/types/strategy';

export const STRATEGY_PHASES: StrategyPhase[] = [
    {
        id: 1,
        name: 'Foundation',
        description: 'Establish core infrastructure, analytics, and basic dashboard.',
        status: 'completed',
        sunTzu: {
            chinese: '始計',
            english: 'Laying Plans',
            meaning: 'Careful planning and calculation before action ensures victory.',
        },
        uiRoute: '/dashboard',
        impact: 'System Stability',
    },
    {
        id: 2,
        name: 'Email & SEO',
        description: 'Setup email drip campaigns and SEO foundation.',
        status: 'missing-ui',
        sunTzu: {
            chinese: '用間',
            english: 'Use of Spies',
            meaning: 'Information gathering and dissemination is key to strategy.',
        },
        uiRoute: '/admin/marketing',
        impact: 'Organic Traffic',
    },
    {
        id: 3,
        name: 'Analytics',
        description: 'Advanced analytics, cohorts, and competitor intelligence.',
        status: 'completed',
        sunTzu: {
            chinese: '知彼知己',
            english: 'Know Enemy',
            meaning: 'Knowing the enemy and yourself leads to 100 victories.',
        },
        uiRoute: '/admin/analytics-dashboard',
        impact: 'Data-Driven Decisions',
    },
    {
        id: 4,
        name: 'Payment',
        description: 'Optimize checkout flow, 1-click upgrades, and pricing tiers.',
        status: 'completed',
        sunTzu: {
            chinese: '兵貴神速',
            english: 'Speed is Essence',
            meaning: 'Swift execution in revenue generation is critical.',
        },
        uiRoute: '/admin/finance',
        impact: '3x Conversion Rate',
    },
    {
        id: 5,
        name: 'Content',
        description: 'Content marketing engine and blog infrastructure.',
        status: 'completed',
        sunTzu: {
            chinese: '以迂為直',
            english: 'Indirect Approach',
            meaning: 'Using content to attract users indirectly is more effective than ads.',
        },
        uiRoute: '/blog',
        impact: 'Brand Authority',
    },
    {
        id: 6,
        name: 'Viral',
        description: 'Referral system, leaderboards, and viral loops.',
        status: 'completed',
        sunTzu: {
            chinese: '致人而不致於人',
            english: 'Pull Strategy',
            meaning: 'Make the enemy (users) come to you.',
        },
        uiRoute: '/admin/viral-economics',
        impact: 'Zero CAC Growth',
    },
    {
        id: 7,
        name: 'Retention',
        description: 'Onboarding flows, win-back campaigns, and churn reduction.',
        status: 'missing-ui',
        sunTzu: {
            chinese: '先為不可勝',
            english: 'Invincibility',
            meaning: 'Secure your defense (retention) before attacking (growth).',
        },
        uiRoute: '/admin/retention',
        impact: 'Low Churn',
    },
    {
        id: 8,
        name: 'Automation',
        description: 'AI agents for support and operations.',
        status: 'completed',
        sunTzu: {
            chinese: '上兵伐謀',
            english: 'Strategy over Fight',
            meaning: 'Win without fighting (manual work) by using strategy (automation).',
        },
        uiRoute: '/admin/agents',
        impact: 'Scalable Ops',
    },
    {
        id: 9,
        name: 'Community',
        description: 'Discord/Twitter integration and community management.',
        status: 'missing-ui',
        sunTzu: {
            chinese: '同舟共濟',
            english: 'Unity',
            meaning: 'United forces are stronger than scattered ones.',
        },
        uiRoute: '/community',
        impact: 'User Loyalty',
    },
    {
        id: 10,
        name: 'System Ops',
        description: 'Infrastructure monitoring, health checks, and system config.',
        status: 'completed',
        sunTzu: {
            chinese: '地',
            english: 'Terrain',
            meaning: 'Understanding the infrastructure terrain is vital.',
        },
        uiRoute: '/admin/system',
        impact: '99.9% Uptime',
    },
    {
        id: 11,
        name: 'Growth',
        description: 'Growth hacking dashboard and experiments.',
        status: 'missing-ui',
        sunTzu: {
            chinese: '勢',
            english: 'Energy',
            meaning: 'Momentum and potential energy drive growth.',
        },
        uiRoute: '/admin/growth',
        impact: 'Exponential Scale',
    },
    {
        id: 12,
        name: 'Optimization',
        description: 'A/B testing and conversion rate optimization.',
        status: 'completed',
        sunTzu: {
            chinese: '虛實',
            english: 'Weak & Strong',
            meaning: 'Attack weaknesses and avoid strengths via testing.',
        },
        uiRoute: '/admin/ab-tests',
        impact: 'Maximized ROI',
    },
    {
        id: 13,
        name: 'Mobile App',
        description: 'React Native mobile application.',
        status: 'completed',
        sunTzu: {
            chinese: '奇正',
            english: 'Surprise/Orthodox',
            meaning: 'Combine standard web (orthodox) with mobile (surprise).',
        },
        uiRoute: '#',
        impact: 'Accessibility',
    },
    {
        id: 14,
        name: 'Enterprise',
        description: 'Enterprise features, SSO, and white-glove support.',
        status: 'completed',
        sunTzu: {
            chinese: '連橫',
            english: 'Alliances',
            meaning: 'Form alliances with powerful partners (enterprises).',
        },
        uiRoute: '/enterprise',
        impact: 'High Ticket Sales',
    },
    {
        id: 15,
        name: 'Simulation',
        description: 'Paper trading and strategy simulation.',
        status: 'completed',
        sunTzu: {
            chinese: '廟算',
            english: 'Temple Calc',
            meaning: 'Simulate battles in the temple before fighting in the field.',
        },
        uiRoute: '/trading/paper',
        impact: 'Risk-Free Onboarding',
    },
    {
        id: 16,
        name: 'Affiliate',
        description: 'Affiliate marketing dashboard and tracking.',
        status: 'completed',
        sunTzu: {
            chinese: '借刀殺人',
            english: 'Borrowed Knife',
            meaning: 'Use others resources (affiliates) to achieve your goals.',
        },
        uiRoute: '/affiliate',
        impact: 'External Growth',
    },
    {
        id: 17,
        name: 'Global',
        description: 'Internationalization and localization.',
        status: 'completed',
        sunTzu: {
            chinese: '天',
            english: 'Heaven/Timing',
            meaning: 'Adapt to different climates (markets) and times.',
        },
        uiRoute: '/i18n',
        impact: 'Global Reach',
    },
    {
        id: 18,
        name: 'Security',
        description: 'Security hardening, audit logs, and compliance.',
        status: 'completed',
        sunTzu: {
            chinese: '守',
            english: 'Defense',
            meaning: 'Invincibility lies in the defense.',
        },
        uiRoute: '/admin/security',
        impact: 'Trust & Safety',
    },
    {
        id: 19,
        name: 'Social',
        description: 'Social trading, copy trading, and leaderboards.',
        status: 'completed',
        sunTzu: {
            chinese: '聚',
            english: 'Gathering',
            meaning: 'Gathering forces creates strength.',
        },
        uiRoute: '/wolf-pack',
        impact: 'Network Effects',
    },
    {
        id: 20,
        name: 'Exit Strategy',
        description: 'Valuation tracking and exit planning.',
        status: 'missing-ui',
        sunTzu: {
            chinese: '走為上',
            english: 'Retreat',
            meaning: 'Knowing when to retreat (exit) is the best strategy.',
        },
        uiRoute: '/admin/finance/valuation',
        impact: 'Liquidity Event',
    },
    {
        id: 21,
        name: 'Telegram',
        description: 'Telegram Mini App integration.',
        status: 'completed',
        sunTzu: {
            chinese: '變',
            english: 'Change',
            meaning: 'Adapt to changing platforms and environments.',
        },
        uiRoute: '#',
        impact: 'Platform Agnostic',
    },
    {
        id: 22,
        name: 'AI Fund',
        description: 'AI-managed investment fund.',
        status: 'missing-ui',
        sunTzu: {
            chinese: '智',
            english: 'Wisdom',
            meaning: 'Use superior wisdom (AI) to outperform.',
        },
        uiRoute: '/invest',
        impact: 'Passive Income',
    },
    {
        id: 23,
        name: 'DAO',
        description: 'Decentralized governance and voting.',
        status: 'completed',
        sunTzu: {
            chinese: '道',
            english: 'The Way',
            meaning: 'Aligning the people with the mission via governance.',
        },
        uiRoute: '/dao',
        impact: 'Community Ownership',
    },
    {
        id: 24,
        name: 'Launchpad',
        description: 'Token launchpad for new projects.',
        status: 'completed',
        sunTzu: {
            chinese: '火攻',
            english: 'Fire Attack',
            meaning: 'Launch explosive attacks (projects) to disrupt the market.',
        },
        uiRoute: '/launchpad',
        impact: 'Ecosystem Growth',
    },
    {
        id: 25,
        name: 'Liquidity',
        description: 'Liquidity provider management.',
        status: 'completed',
        sunTzu: {
            chinese: '水',
            english: 'Water',
            meaning: 'Be formless and adaptable like water (liquidity).',
        },
        uiRoute: '/admin/providers',
        impact: 'Market Depth',
    },
    {
        id: 26,
        name: 'Launch',
        description: 'Official public launch event.',
        status: 'missing-ui',
        sunTzu: {
            chinese: '戰',
            english: 'War',
            meaning: 'The final battle for market dominance.',
        },
        uiRoute: '/launch',
        impact: 'Market Entry',
    },
    {
        id: 27,
        name: 'Mobile Empire',
        description: 'Dominance in mobile app stores.',
        status: 'completed',
        sunTzu: {
            chinese: '霸',
            english: 'Hegemony',
            meaning: 'Establishing dominance over the mobile terrain.',
        },
        uiRoute: '#',
        impact: 'Market Leadership',
    },
    {
        id: 28,
        name: 'White Label',
        description: 'White label solution for B2B partners.',
        status: 'missing-ui',
        sunTzu: {
            chinese: '分',
            english: 'Division',
            meaning: 'Divide and conquer by enabling others.',
        },
        uiRoute: '/admin/whitelabel',
        impact: 'B2B Revenue',
    },
    {
        id: 29,
        name: 'Algo Studio',
        description: 'Visual strategy builder for users.',
        status: 'completed',
        sunTzu: {
            chinese: '工',
            english: 'Craft',
            meaning: 'Mastering the craft of strategy building.',
        },
        uiRoute: '/studio',
        impact: 'User Innovation',
    },
    {
        id: 30,
        name: 'Singularity',
        description: 'The Hive Mind - AI Superintelligence.',
        status: 'missing-ui',
        sunTzu: {
            chinese: '天人合一',
            english: 'Unity',
            meaning: 'Heaven (AI) and Man (User) become one.',
        },
        uiRoute: '/admin/singularity',
        impact: 'Infinite Scale',
    },
];
