import { getCommissionRate, type TierId } from '@apex-os/vibe-payment';
import { logger } from '@/lib/logger';
import { getSupabaseClient } from '@/lib/supabase';
import { EXCHANGE_AVG_REBATE_RATE, TIERS } from './tier-manager';

interface TradeExecution {
  user_id: string;
  volume: number;
  fee: number; // Actual fee paid
  exchange: string;
  symbol: string;
  trade_id?: string;
}

export async function processTradeCommission(trade: TradeExecution) {
  const supabase = getSupabaseClient();
  const { user_id, volume, exchange, symbol, trade_id } = trade;

  try {
    // 1. Calculate User's Own Rebate (Self-Rebate)
    // =============================================

    // Fetch user tier
    const { data: userTierData } = await supabase.from('user_tiers').select('tier').eq('user_id', user_id).single();

    const userTier = (userTierData?.tier || 'FREE') as keyof typeof TIERS;
    const tierConfig = TIERS[userTier];

    // CRITICAL: Use actual fee from exchange. Zero-fee pairs = ZERO revenue.
    // If we use volume * avg_rate on zero-fee pairs, we pay out money we didn't earn.
    const PARTNER_COMMISSION_SHARE = 0.4;

    let revenueGenerated = 0;

    if (typeof trade.fee === 'number' && trade.fee > 0) {
      revenueGenerated = trade.fee * PARTNER_COMMISSION_SHARE;
    } else if (typeof trade.fee === 'number' && trade.fee === 0) {
      // Zero-fee pair (e.g. BTC/FDUSD) — no revenue, no commissions
      logger.info(`[Commission] Zero-fee trade ${trade_id} on ${symbol}. No commission generated.`);
      return; // Early exit — nothing to distribute
    } else {
      // Fee missing — use conservative estimation with warning
      logger.warn(`[Commission] Missing fee for trade ${trade_id}, using volume estimation.`);
      revenueGenerated = volume * EXCHANGE_AVG_REBATE_RATE;
    }

    // User gets a % of that revenue based on their tier's rebate setting
    const userSelfRebate = revenueGenerated * tierConfig.rebate;

    if (userSelfRebate > 0) {
      const { error: creditError } = await supabase.rpc('credit_user_balance_realtime', {
        p_user_id: user_id,
        p_amount: userSelfRebate,
        p_source: 'trading_rebate',
        p_metadata: {
          trade_volume: volume,
          exchange: exchange,
          symbol: symbol,
          tier: userTier,
          trade_id,
        },
      });

      if (creditError) {
        logger.error('Failed to credit self-rebate:', creditError);
      }
    }

    // 2. Calculate Referral Commissions (L1-L4)
    // =========================================

    // Find upstream referrers: who invited this user?
    const { data: referrers } = await supabase
      .from('referral_network')
      .select('referrer_id, level')
      .eq('referee_id', user_id)
      .lte('level', 4); // Only up to L4

    if (referrers && referrers.length > 0) {
      // The "Commission Pot" is the remainder after self-rebate?
      // OR is it calculated from the full revenue?
      // unified-tiers.ts defines rates like "20% direct referrals".
      // Usually this means 20% of the REVENUE generated.
      // If we use (1 - rebate), we might underpay if rebate is high.
      // Let's assume the rates in unified-tiers are percentages of the REVENUE.
      // Example: PRO earns 20% of the revenue generated by their referral.

      // However, we must ensure we don't pay out more than 100% of revenue.
      // Revenue = 100%
      // Self Rebate (PRO) = 60%
      // Commission L1 (PRO) = 20%
      // Commission L2 (PRO) = 10%
      // Commission L3 (PRO) = 5%
      // Total = 95% -> Safe.

      // So we apply the rate directly to `revenueGenerated`.

      for (const ref of referrers) {
        // Get referrer's tier
        const { data: refTierData } = await supabase
          .from('user_tiers')
          .select('tier')
          .eq('user_id', ref.referrer_id)
          .single();

        if (!refTierData) continue;

        const refTier = (refTierData.tier || 'FREE').toUpperCase() as TierId;

        // CRITICAL FIX: Use explicit rate from unified-tiers.ts
        // Do NOT use generic multipliers or DB stored total rates.
        const commissionRate = getCommissionRate(refTier, ref.level as 1 | 2 | 3 | 4);

        // Commission amount = Revenue * Rate
        const commissionAmount = revenueGenerated * commissionRate;

        if (commissionAmount > 0) {
          await supabase.rpc('credit_user_balance_realtime', {
            p_user_id: ref.referrer_id,
            p_amount: commissionAmount,
            p_source: `l${ref.level}_commission`,
            p_metadata: {
              from_user: user_id,
              trade_volume: volume,
              level: ref.level,
              trade_id,
              referrer_tier: refTier,
              applied_rate: commissionRate,
            },
          });
        }
      }
    }

    // 3. Update User Metrics (Async - fire and forget or update `user_tiers`)
    // We should increment `monthly_volume`.
    // `user_tiers` has `monthly_volume`.
    // Let's update it.
    try {
      await supabase.rpc('increment_user_volume', {
        p_user_id: user_id,
        p_volume: volume,
      });
    } catch {
      // Fallback: direct update if RPC not available
      const { data: existing } = await supabase
        .from('user_tiers')
        .select('monthly_volume, total_volume')
        .eq('user_id', user_id)
        .single();

      if (existing) {
        await supabase
          .from('user_tiers')
          .update({
            monthly_volume: (existing.monthly_volume || 0) + volume,
            total_volume: (existing.total_volume || 0) + volume,
            updated_at: new Date().toISOString(),
          })
          .eq('user_id', user_id);
      }
    }
  } catch (error) {
    logger.error('ProcessTradeCommission Error:', error);
    throw error; // Re-throw for caller to handle
  }
}
