-- ============================================
-- APEX SMART-SWITCH: Sub-Account Verification Tables
-- Migration 003: Exchange verification infrastructure
-- ============================================

-- Table 1: Exchange Broker Configurations (Apex credentials)
-- ===========================================================
CREATE TABLE IF NOT EXISTS public.exchange_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exchange TEXT NOT NULL CHECK (exchange IN ('binance', 'bybit', 'okx')),
  broker_api_key_encrypted TEXT NOT NULL,
  broker_api_secret_encrypted TEXT NOT NULL,
  broker_uid TEXT,  -- Apex's broker UID/code (e.g., Binance broker ID, Bybit affiliate code)
  is_active BOOLEAN DEFAULT TRUE,
  config_metadata JSONB DEFAULT '{}',  -- Store IP whitelist, rate limits, etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes for quick lookup
CREATE INDEX IF NOT EXISTS idx_exchange_configs_exchange_active
  ON public.exchange_configs(exchange, is_active) WHERE is_active = TRUE;

-- Partial unique constraint: One active config per exchange
CREATE UNIQUE INDEX IF NOT EXISTS idx_exchange_configs_unique_active
  ON public.exchange_configs(exchange) WHERE is_active = TRUE;

-- RLS Policies (super_admin only)
ALTER TABLE public.exchange_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Super admins view exchange configs" ON public.exchange_configs
  FOR SELECT USING (
    (SELECT role FROM public.users WHERE id = auth.uid()) = 'super_admin'
  );

CREATE POLICY "Super admins manage exchange configs" ON public.exchange_configs
  FOR ALL USING (
    (SELECT role FROM public.users WHERE id = auth.uid()) = 'super_admin'
  );

-- Table 2: User Exchange Accounts (User-submitted UIDs)
-- =======================================================
CREATE TABLE IF NOT EXISTS public.user_exchange_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  exchange TEXT NOT NULL CHECK (exchange IN ('binance', 'bybit', 'okx')),
  user_uid TEXT NOT NULL,  -- User-submitted UID (e.g., Binance 9-digit UID, Bybit 7-8 digit UID)
  verification_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (verification_status IN ('pending', 'verified', 'failed', 'manual_review')),
  verification_method TEXT DEFAULT 'api' CHECK (verification_method IN ('api', 'manual')),
  verification_metadata JSONB DEFAULT '{}',  -- Store API response details, error codes
  verified_at TIMESTAMP WITH TIME ZONE,
  failed_reason TEXT,  -- Store error message if verification fails
  retry_count INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,

  -- Constraint: One UID per user per exchange
  UNIQUE(user_id, exchange)
);

-- Indexes for verification queries
CREATE INDEX IF NOT EXISTS idx_user_exchange_accounts_user_status
  ON public.user_exchange_accounts(user_id, verification_status);

CREATE INDEX IF NOT EXISTS idx_user_exchange_accounts_exchange_status
  ON public.user_exchange_accounts(exchange, verification_status);

CREATE INDEX IF NOT EXISTS idx_user_exchange_accounts_pending
  ON public.user_exchange_accounts(verification_status, created_at DESC)
  WHERE verification_status IN ('pending', 'manual_review');

-- RLS Policies (Users view own, admins view all)
ALTER TABLE public.user_exchange_accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users view own exchange accounts" ON public.user_exchange_accounts
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Super admins view all exchange accounts" ON public.user_exchange_accounts
  FOR SELECT USING (
    (SELECT role FROM public.users WHERE id = auth.uid()) = 'super_admin'
  );

CREATE POLICY "Users can insert own exchange accounts" ON public.user_exchange_accounts
  FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY "Service role can update verification status" ON public.user_exchange_accounts
  FOR UPDATE USING (
    current_setting('request.jwt.claims', true)::json->>'role' = 'service_role'
  );

-- Table 3: Verification Audit Log (Forensic trail)
-- ==================================================
CREATE TABLE IF NOT EXISTS public.verification_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  exchange TEXT NOT NULL,
  user_uid TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('verify_attempt', 'verify_success', 'verify_failed', 'manual_approve', 'manual_reject', 'fraud_detected')),
  verification_result JSONB DEFAULT '{}',  -- Store API response, fraud signals
  ip_address INET,
  user_agent TEXT,
  device_fingerprint TEXT,  -- For fraud detection
  admin_id UUID REFERENCES public.users(id) ON DELETE SET NULL,  -- For manual actions
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes for audit queries
CREATE INDEX IF NOT EXISTS idx_verification_audit_user_created
  ON public.verification_audit_log(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_verification_audit_exchange_created
  ON public.verification_audit_log(exchange, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_verification_audit_action_created
  ON public.verification_audit_log(action, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_verification_audit_ip_created
  ON public.verification_audit_log(ip_address, created_at DESC);

-- RLS Policies (Append-only, super_admin view all)
ALTER TABLE public.verification_audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Super admins view all verification audits" ON public.verification_audit_log
  FOR SELECT USING (
    (SELECT role FROM public.users WHERE id = auth.uid()) = 'super_admin'
  );

CREATE POLICY "Users view own verification audits" ON public.verification_audit_log
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Service role can insert verification audits" ON public.verification_audit_log
  FOR INSERT WITH CHECK (
    current_setting('request.jwt.claims', true)::json->>'role' = 'service_role'
  );

-- NO UPDATE/DELETE POLICIES = IMMUTABLE AUDIT LOG

-- ============================================
-- Verification Queries
-- ============================================

-- Test: Insert sample exchange config (replace with real values)
INSERT INTO public.exchange_configs (exchange, broker_api_key_encrypted, broker_api_secret_encrypted, broker_uid)
VALUES ('binance', 'gAAAAABl...', 'gAAAAABl...', '12345678');  -- Use VaultService.encrypt_secret()

-- Test: Insert sample user exchange account
-- INSERT INTO public.user_exchange_accounts (user_id, exchange, user_uid)
-- VALUES ('existing-user-uuid', 'binance', '123456789');

-- Cleanup test data
DELETE FROM public.exchange_configs WHERE broker_uid = '12345678';

-- ============================================
-- Migration Complete
-- ============================================

DO $$
BEGIN
  RAISE NOTICE '✅ Migration 003: Exchange verification tables created';
  RAISE NOTICE '   - exchange_configs: Apex broker credentials';
  RAISE NOTICE '   - user_exchange_accounts: User-submitted UIDs';
  RAISE NOTICE '   - verification_audit_log: Forensic trail';
  RAISE NOTICE '✅ RLS policies applied for security';
  RAISE NOTICE '🔄 APEX SMART-SWITCH database foundation complete';
END$$;
