-- 🔒 SECURITY HARDENING PATCH 🔒
-- Generated by Gemini Security Auditor
-- Date: 2025-11-29

-- 1. FIX: Enable RLS on sensitive 'system_settings' table
-- Risk: Without RLS, this table might be publicly readable.
ALTER TABLE IF EXISTS system_settings ENABLE ROW LEVEL SECURITY;

-- Policy: Only Service Role (Backend) can modify settings
DROP POLICY IF EXISTS "Service Role Full Access" ON system_settings;
CREATE POLICY "Service Role Full Access" 
ON system_settings 
FOR ALL 
TO service_role 
USING (true) 
WITH CHECK (true);

-- Policy: Admins can view (assuming you verify admin via Middleware/Edge Function before querying)
-- Ideally, keep this table private to Service Role only.
-- If frontend needs to read it, create a secure RPC function.

-- 2. FIX: Add index to Foreign Keys to prevent CPU DoS
-- Risk: Large table joins without index cause 100% CPU usage.
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_user_id ON withdrawals(user_id);

-- 3. FIX: Data Validation Constraint for Discount Codes
-- Risk: Negative prices or >100% discount.
ALTER TABLE IF EXISTS discount_codes 
ADD CONSTRAINT check_discount_value_valid 
CHECK (
    (discount_type = 'percentage' AND discount_value > 0 AND discount_value <= 100) OR
    (discount_type = 'fixed' AND discount_value > 0)
);

-- 4. FIX: Cleanup Policy (Optional but recommended)
-- Ensure 'api_keys' table RLS is strict
ALTER TABLE IF EXISTS api_keys ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own api keys" ON api_keys;
CREATE POLICY "Users can view own api keys" 
ON api_keys 
FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create own api keys" ON api_keys;
CREATE POLICY "Users can create own api keys" 
ON api_keys 
FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own api keys" ON api_keys;
CREATE POLICY "Users can delete own api keys" 
ON api_keys 
FOR DELETE 
TO authenticated 
USING (auth.uid() = user_id);

-- 5. NOTE ON API KEYS ENCRYPTION
-- This SQL script cannot retrospectively encrypt existing plain-text keys easily without logic.
-- Please run a separate migration script in your Backend code to:
-- 1. Read all api_keys.
-- 2. Hash them using bcrypt.
-- 3. Update the table.
-- 4. Then ALTER TABLE api_keys DROP COLUMN secret_key (and rename hashed_key column).

