-- 🔒 SECURITY HARDENING PATCH 🔒
-- Generated by Gemini Security Auditor
-- Date: 2025-11-29

-- 1. FIX: Enable RLS on sensitive 'system_settings' table
-- Risk: Without RLS, this table might be publicly readable.
CREATE TABLE IF NOT EXISTS system_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE IF EXISTS system_settings ENABLE ROW LEVEL SECURITY;

-- Policy: Only Service Role (Backend) can modify settings
DROP POLICY IF EXISTS "Service Role Full Access" ON system_settings;
CREATE POLICY "Service Role Full Access"
ON system_settings
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Policy: Admins can view (assuming you verify admin via Middleware/Edge Function before querying)
-- Ideally, keep this table private to Service Role only.
-- If frontend needs to read it, create a secure RPC function.

-- 2. FIX: Add index to Foreign Keys to prevent CPU DoS
-- Risk: Large table joins without index cause 100% CPU usage.

-- Ensure 'withdrawals' table exists
CREATE TABLE IF NOT EXISTS withdrawals (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    admin_id UUID REFERENCES admin_users(id),
    amount DECIMAL(20, 8) NOT NULL,
    currency TEXT DEFAULT 'USDT' NOT NULL,
    destination_address TEXT NOT NULL,
    status TEXT DEFAULT 'PENDING',
    tx_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure 'orders' table exists
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    side VARCHAR(10) NOT NULL,
    type VARCHAR(20) NOT NULL,
    quantity NUMERIC NOT NULL,
    price NUMERIC,
    status VARCHAR(20) DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_user_id ON withdrawals(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);

-- Safe index creation for transactions (might be missing)
DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'transactions') THEN
        CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
    END IF;
END $$;

-- CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id); -- Skipped: Column user_id missing in some envs

-- 3. FIX: Data Validation Constraint for Discount Codes
-- Risk: Negative prices or >100% discount.

-- Ensure 'discount_codes' table exists
CREATE TABLE IF NOT EXISTS discount_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL,
  discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
  discount_value NUMERIC NOT NULL,
  valid_from TIMESTAMPTZ DEFAULT NOW(),
  valid_until TIMESTAMPTZ,
  max_uses INTEGER,
  current_uses INTEGER DEFAULT 0,
  applicable_tiers TEXT[],
  minimum_purchase NUMERIC,
  created_by UUID REFERENCES auth.users(id),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE IF EXISTS discount_codes
DROP CONSTRAINT IF EXISTS check_discount_value_valid;

ALTER TABLE IF EXISTS discount_codes
ADD CONSTRAINT check_discount_value_valid
CHECK (
    (discount_type = 'percentage' AND discount_value > 0 AND discount_value <= 100) OR
    (discount_type = 'fixed' AND discount_value > 0)
);

-- 4. FIX: Cleanup Policy (Optional but recommended)
-- Ensure 'api_keys' table RLS is strict

-- Ensure 'api_keys' table exists
CREATE TABLE IF NOT EXISTS api_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    label VARCHAR(50),
    access_key VARCHAR(64) NOT NULL UNIQUE,
    secret_key VARCHAR(255) NOT NULL,
    permissions JSONB DEFAULT '["read", "trade"]',
    last_used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true
);

ALTER TABLE IF EXISTS api_keys ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own api keys" ON api_keys;
CREATE POLICY "Users can view own api keys"
ON api_keys
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create own api keys" ON api_keys;
CREATE POLICY "Users can create own api keys"
ON api_keys
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own api keys" ON api_keys;
CREATE POLICY "Users can delete own api keys"
ON api_keys
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- 5. NOTE ON API KEYS ENCRYPTION
-- This SQL script cannot retrospectively encrypt existing plain-text keys easily without logic.
-- Please run a separate migration script in your Backend code to:
-- 1. Read all api_keys.
-- 2. Hash them using bcrypt.
-- 3. Update the table.
-- 4. Then ALTER TABLE api_keys DROP COLUMN secret_key (and rename hashed_key column).
